version: "3.7"

services:
  #################################################################
  # ddclient
  #################################################################
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    # Hier die Env-Datei angeben (analog wireguard.env):
    env_file: ddns-updater.env
    volumes:
      - ./config:/config
    restart: unless-stopped