services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      PUID: '1004'
      PGID: '100'    
    volumes:
      - ./config:/config
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      # HTTP zu HTTPS Weiterleitung
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.authelia.entrypoints=web"
      - "traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.routers.authelia.middlewares=redirect-to-https@docker"

      # HTTPS Konfiguration
      - "traefik.http.routers.authelia-secure.entrypoints=websecure"
      - "traefik.http.routers.authelia-secure.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.routers.authelia-secure.service=authelia"
      - "traefik.http.routers.authelia-secure.tls=true"
      - "traefik.http.routers.authelia-secure.tls.certresolver=http_resolver"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"

      # Authelia Middleware Definition
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${DOMAIN}"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
    restart: unless-stopped

networks:
  proxy:
    external: true
