services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    environment:
      - PUID=1004
      - PGID=131
      - TZ=Europe/Berlin
      - PASSWORD=test
    volumes:
      - code-server-config:/config
      - code-server-projects:/projects
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.rule=Host(`code.${DOMAIN}`)"
      - "traefik.http.routers.code-server.tls=true"
      - "traefik.http.routers.code-server.tls.certresolver=http_resolver"
      - "traefik.http.services.code-server.loadbalancer.server.port=8080"
      - "traefik.http.routers.code-server.middlewares=default@file,traefikAuth@file"

volumes:
  code-server-config:
  code-server-projects:

networks:
  proxy:
    external: true
