---
theme: dark
default_redirection_url: https://auth.$DOMAIN

server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: info

totp:
  issuer: authelia.$DOMAIN

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: two_factor
  rules:
    - domain: "*.$DOMAIN"
      policy: two_factor

session:
  secret: $secret
  expiration: 3600
  inactivity: 300
  domain: $DOMAIN
  remember_me: true
  same_site: lax

storage:
  encryption_key: $encryption_key
  local:
    path: /config/db.sqlite3

# Ersetze filesystem notifier mit SMTP
notifier:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: $EMAIL
    password: "vaky nwgq jgfs vejw"  # Ersetze dies mit deinem App-Passwort
    sender: $EMAIL
    identifier: $DOMAIN
    subject: "[Authelia] {title}"
    startup_check_address: $EMAIL
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

identity_validation:
  reset_password:
    jwt_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXS
