{ config, lib, pkgs, getModuleConfig, moduleName, ... }:

let
  cfg = getModuleConfig moduleName;
  catalog = import ./lib/rice-catalog.nix { inherit pkgs; };
  paths = import ./lib/paths.nix;

  isApplyable = rice:
    let method = rice.applyMethod or "reference";
    in (method == "dotfiles" && (rice.dotfiles.cloneUrl or "") != "")
      || (method == "flake" && rice ? flake && (rice.flake.url or "") != "")
      || (method == "wallpaper" && rice.thumbnailHash != null);

  wallpaperRiceId =
    cfg.wallpaper.rice or cfg.rice or null;

  selectedRice =
    if cfg.rice != null then catalog.${cfg.rice} or null else null;

  wallpaperRice =
    if wallpaperRiceId != null then catalog.${wallpaperRiceId} or null else null;

  wallpaperFile =
    if cfg.wallpaper.path != null then cfg.wallpaper.path
    else if wallpaperRice != null && wallpaperRice.thumbnailHash != null then
      "${pkgs.fetchurl {
        url = wallpaperRice.thumbnailUrl;
        hash = wallpaperRice.thumbnailHash;
      }}"
    else null;

  hyprpaperConf =
    if wallpaperFile != null then ''
      preload = ${wallpaperFile}
      wallpaper = ,${wallpaperFile}
    '' else "";

  riceMethod = selectedRice.applyMethod or "reference";
  usesCollection = riceMethod == "dotfiles" || riceMethod == "flake";

  hyprHeader =
    let
      riceHint =
        if selectedRice != null then ''
          # Rice: ${selectedRice.name} by ${selectedRice.creator}
          # Apply: ${riceMethod}
          # Dotfiles: ${selectedRice.dotfilesUrl or "—"}
        '' else "";
      execLines = lib.concatStringsSep "\n" (
        lib.optional (cfg.packages.hyprpaper or true && wallpaperFile != null)
          "exec-once = hyprpaper -c /etc/hypr/hyprpaper.conf"
        ++ lib.optional (cfg.packages.waybar or true)
          "exec-once = waybar"
      );
    in lib.concatStringsSep "\n" (
      lib.filter (s: s != "") [
        "# Generated by NCC hyprland module"
        riceHint
        execLines
      ]
    );

  hyprLuaHeader =
    if selectedRice != null then ''
      -- Generated by NCC hyprland module
      -- Rice: ${selectedRice.name} by ${selectedRice.creator}
      -- Apply: ${riceMethod}
    '' else ''
      -- Generated by NCC hyprland module
    '';

  wallpaperOnlyConf = lib.concatStringsSep "\n" (
    lib.filter (s: s != "") [
      hyprHeader
      cfg.extraConfig or ""
    ]
  );

  hyprlandConfFile = lib.mkIf (!usesCollection && wallpaperOnlyConf != "") {
    text = wallpaperOnlyConf;
    mode = "0644";
  };
in
lib.mkIf (cfg.enable or false) {
  programs.hyprland = {
    enable = true;
    xwayland.enable = true;
  };

  environment.etc."xdg/hypr/hyprland.conf" = hyprlandConfFile;

  environment.etc."hypr/hyprpaper.conf" = lib.mkIf
    (cfg.packages.hyprpaper or true && hyprpaperConf != "")
    { text = hyprpaperConf; mode = "0644"; };

  environment.systemPackages = lib.optional (cfg.packages.hyprpaper or true) pkgs.hyprpaper
    ++ lib.optional (cfg.packages.waybar or true) pkgs.waybar
    ++ [ pkgs.jq ]
    ++ lib.filter (p: p != null) (
      map (name: lib.attrByPath (lib.splitString "." name) null pkgs)
        (selectedRice.requiredPackages or [])
    );

  systemd.tmpfiles.rules = [
    "d ${paths.stateRoot} 0755 root root -"
    "d ${paths.collectionsRoot} 0755 root root -"
  ];

  system.activationScripts.nccHyprlandRice = lib.stringAfter [ "etc" ] ''
    install -d -m 0755 ${paths.stateRoot} ${paths.collectionsRoot}
    manifest="${paths.activeManifest}"
    conf_dest="${paths.hyprConfigDest}"
    lua_dest="${paths.hyprConfigDestLua}"
    if [ -f "$manifest" ]; then
      method=$(${pkgs.jq}/bin/jq -r '.applyMethod // ""' "$manifest")
      case "$method" in
        dotfiles|flake)
          root=$(${pkgs.jq}/bin/jq -r '.collectionDir // ""' "$manifest")
          rel=$(${pkgs.jq}/bin/jq -r '.hyprConfig // ""' "$manifest")
          if [ -n "$root" ] && [ -n "$rel" ] && [ -f "$root/upstream/$rel" ]; then
            if [[ "$rel" == *.lua ]]; then
              hypr_tree="$root/upstream/$(dirname "$rel")"
              mkdir -p "$(dirname "$lua_dest")"
              if [[ -d "$hypr_tree" ]]; then
                ${pkgs.rsync}/bin/rsync -a --delete "$hypr_tree/" "$(dirname "$lua_dest")/"
              else
                mkdir -p "$(dirname "$lua_dest")"
                cp -f "$root/upstream/$rel" "$lua_dest"
              fi
              if [[ -f "$lua_dest" ]]; then
                tmp_lua=$(mktemp)
                {
                  cat <<'NCC_HDR'
${hyprLuaHeader}
NCC_HDR
                  cat "$lua_dest"
                  if [ -n "${cfg.extraConfig or ""}" ]; then
                    cat <<'NCC_EXTRA'
${cfg.extraConfig or ""}
NCC_EXTRA
                  fi
                } > "$tmp_lua"
                mv -f "$tmp_lua" "$lua_dest"
                chmod 0644 "$lua_dest"
              fi
              rm -f "$conf_dest"
            else
              mkdir -p "$(dirname "$conf_dest")"
              {
                cat <<'NCC_HDR'
${hyprHeader}
NCC_HDR
                echo "source = $root/upstream/$rel"
                if [ -n "${cfg.extraConfig or ""}" ]; then
                  cat <<'NCC_EXTRA'
${cfg.extraConfig or ""}
NCC_EXTRA
                fi
              } > "$conf_dest"
              chmod 0644 "$conf_dest"
              rm -f "$lua_dest"
            fi
          else
            echo "ncc-hyprland: collection missing for active rice — run: sudo ncc hyprland rice install --from-set" >&2
          fi
          ;;
        wallpaper)
          if [ ! -f "$conf_dest" ] && [ ! -f "$lua_dest" ]; then
            mkdir -p "$(dirname "$conf_dest")"
            cat > "$conf_dest" <<'NCC_WALL'
${wallpaperOnlyConf}
NCC_WALL
            chmod 0644 "$conf_dest"
          fi
          ;;
      esac
    elif [ -n "${wallpaperOnlyConf}" ] && [ ! -f "$conf_dest" ] && [ ! -f "$lua_dest" ]; then
      mkdir -p "$(dirname "$conf_dest")"
      cat > "$conf_dest" <<'NCC_FALLBACK'
${wallpaperOnlyConf}
NCC_FALLBACK
      chmod 0644 "$conf_dest"
    fi
  '';

  assertions = [
    {
      assertion = cfg.rice == null || catalog ? ${cfg.rice};
      message = "hyprland.rice '${cfg.rice}' is not in the rice catalog.";
    }
    {
      assertion =
        cfg.rice == null
        || selectedRice == null
        || isApplyable selectedRice;
      message = "hyprland.rice '${cfg.rice}' is not installable. Use: ncc hyprland rice list";
    }
    {
      assertion =
        cfg.wallpaper.rice == null
        || catalog ? ${cfg.wallpaper.rice};
      message = "hyprland.wallpaper.rice '${cfg.wallpaper.rice}' is not in the rice catalog.";
    }
    {
      assertion =
        wallpaperFile != null
        || (cfg.wallpaper.path == null && wallpaperRiceId == null)
        || (wallpaperRice != null && wallpaperRice.thumbnailHash != null)
        || cfg.wallpaper.path != null;
      message = ''
        Selected wallpaper rice '${toString wallpaperRiceId}' has no bundled thumbnail hash.
        Set hyprland.wallpaper.path to a local file or pick a catalog rice with thumbnailHash.
      '';
    }
  ];
}
