services:

  yourls:
    image: yourls
    restart: always
    container_name: yoURLs
    networks:
      proxy:
    dns:
#      - 172.40.0.3
      - 8.8.8.8
      - 1.1.1.1
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.link-secure.entrypoints: websecure
      traefik.http.routers.link-secure.middlewares: default@file,link-whitelist@docker
      traefik.http.routers.link-secure.rule: Host(`link.${DOMAIN}`)
      traefik.http.routers.link-secure.service: link
      traefik.http.routers.link-secure.tls: "true"
      traefik.http.routers.link-secure.tls.certresolver: http_resolver
      traefik.http.routers.link.entrypoints: web
      traefik.http.routers.link.rule: Host(`link.${DOMAIN}`)
      traefik.http.services.link.loadbalancer.server.port: "80"
      traefik.http.middlewares.link-whitelist.ipwhitelist.sourcerange: "192.168.0.0/16,10.0.0.0/8"
      

  yourls-db:
    image: mysql
    restart: always
    networks: 
      default:
    env_file: env.mysql
    volumes:
#      - ./mysql_yourls_db:/var/lib/mysql
      - ./data:/var/lib/mysql

networks:
  proxy:
    external: true
