services:

  crowdsec:
    container_name: crowdsec
    env_file: crowdsec.env
    hostname: crowdsec
    healthcheck:
      test: ["CMD", "cscli", "version"]
      interval: 20s
      timeout: 2s
      retries: 5
      start_period: 10s
    image: crowdsecurity/crowdsec:latest
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      crowdsec:
        ipv4_address: 172.41.254.254
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/traefik:/var/log/traefik:ro
      - ./crowdsec/config:/etc/crowdsec
      - ./crowdsec/data:/var/lib/crowdsec/data

  traefik:
    container_name: traefik
    depends_on:
      crowdsec:
        condition: service_healthy
    env_file: traefik.env
    hostname: traefik
    command:
      - "--log.level=DEBUG"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s
    image: traefik:v3.1.0
    labels:
      # Basis-Konfiguration
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"

      # Router Konfiguration
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=default@file,traefikAuth@file,admin-whitelist@file"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=http_resolver"
      
      # Service Konfiguration
      - "traefik.http.services.traefik.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.traefik.loadbalancer.sticky.cookie.secure=true"
      
      # Ping Router 
      - "traefik.http.routers.pingweb.rule=PathPrefix(`/ping`)"
      - "traefik.http.routers.pingweb.service=ping@internal"
      - "traefik.http.routers.pingweb.entrypoints=websecure"

      # Middleware Definitionen (verfügbar für andere Services)
      # Security Headers
      - "traefik.http.middlewares.security-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.security-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.security-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      
      # Zusätzliche Security Headers
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.referrerPolicy=same-origin"
      - "traefik.http.middlewares.security-headers.headers.permissionsPolicy=camera=(), microphone=(), geolocation=()"
      - "traefik.http.middlewares.security-headers.headers.contentSecurityPolicy=default-src 'self'; frame-ancestors 'none'"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow"
      
      # Rate Limiting
      - "traefik.http.middlewares.rate-limit.ratelimit.average=10"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=50"
      - "traefik.http.middlewares.rate-limit.ratelimit.period=1m"
      
    networks:
      crowdsec:
        ipv4_address: 172.41.254.253
      proxy:
        ipv4_address: 172.40.255.254
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"  # Erreichbar über alle Server-IPs
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik/:/var/log/traefik/
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme_letsencrypt.json:/acme_letsencrypt.json
      - ./traefik/tls_letsencrypt.json:/tls_letsencrypt.json
#      - ./traefik/dynamic_conf.yml:/dynamic_conf.yml
      - ./traefik/dynamic-conf:/dynamic-conf:ro

  traefik_crowdsec_bouncer:
    container_name: traefik_crowdsec_bouncer
    depends_on:
      crowdsec:
        condition: service_healthy
    env_file: traefik-crowdsec-bouncer.env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    hostname: traefik-crowdsec-bouncer
    image: fbonalair/traefik-crowdsec-bouncer:latest
    networks:
      crowdsec:
        ipv4_address: 172.41.254.252
    restart: unless-stopped

  ip-updater:
    image: alpine:latest
    container_name: ip-updater
    restart: unless-stopped
    volumes:
      - ./traefik/dynamic-conf:/dynamic-conf:rw
    command: |
      sh -c 'while true; do
        apk add --no-cache curl
        PUBLIC_IP=$$(curl -s https://api.ipify.org)
        echo "Current public IP: $$PUBLIC_IP"
        echo -e "http:\n  middlewares:\n    admin-whitelist:\n      ipWhiteList:\n        sourceRange:\n          - \"192.168.0.0/16\"\n          - \"10.8.0.0/24\"\n          - \"172.16.0.0/12\"\n          - \"172.40.0.0/16\"\n          - \"172.41.0.0/16\"\n          - \"$$PUBLIC_IP/32\"" > /dynamic-conf/custom-ips.yml
        echo "Updated IP whitelist configuration"
        sleep 14400
      done'
    
networks:
  proxy:
    name: proxy
    driver: bridge
    ipam:
      config:
      - subnet: 172.40.0.0/16
    attachable: true
  crowdsec:
    name: crowdsec
    driver: bridge
    ipam:
      config:
      - subnet: 172.41.0.0/16
    attachable: true

