services:

  endlessh:
    container_name: endlessh
    environment:
      - PUID=${UID}
      - PGID=${GID}
    image: shizunge/endlessh-go:latest
    restart: always
    command:
      - -interval_ms=1000
      - -logtostderr
      - -v=1
      - -enable_prometheus
      - -geoip_supplier=ip-api
    networks:
      proxy:
    ports:
      - "2222:2222"  # SSH Honeypot port
      - "127.0.0.1:2112:2112"  # Prometheus metrics (nur lokal)

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-SSH
    environment:
      - PUID=${UID}
      - PGID=${GID}
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=45d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-admin-api
    networks:
      proxy:
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    labels:
      # Basis-Konfiguration
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      # Router Konfiguration
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=http_resolver"
      
      # Service Konfiguration
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      
      # Maximale Sicherheit
      - "traefik.http.routers.prometheus.middlewares=default@file,traefikAuth@file,admin-whitelist@file,rate-limit@docker"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-SSH
    environment:
      - PUID=${UID}
      - PGID=${GID}
    restart: always
    networks:
      proxy:
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file:
      - grafana.env
    volumes:
      - grafana_var:/var/lib/grafana/
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
    labels:
      # Basis-Konfiguration
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      # Router Konfiguration
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=http_resolver"
      
      # Service Konfiguration
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      
      # Maximale Sicherheit
      - "traefik.http.routers.grafana.middlewares=default@file,traefikAuth@file,admin-whitelist@file,rate-limit@docker"
      
      # Sticky Sessions für Grafana
      - "traefik.http.services.grafana.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.grafana.loadbalancer.sticky.cookie.secure=true"

networks:
  proxy:
    external: true

volumes:
  prometheus:
  grafana_var:
