{ config, lib, pkgs, ... }:
let
  pythonEnv = pkgs.python312.withPackages (ps: with ps; [
    pytest
    pytest-asyncio
    pytest-cov
    pytest-mock
    httpx
    structlog
    colorama
    psutil
    requests
    pillow
    sqlalchemy
    asyncpg
    alembic
    psycopg2
    black
    mypy
    pylint
    ipython
    jupyter
    notebook
    fastapi
    uvicorn
    pydantic
    pydantic-settings
    python-multipart
    cryptography
    python-jose
    passlib
    bcrypt
    python-dotenv
    py-cpuinfo
    speedtest-cli
    pyyaml
    email-validator
  ]);
in
{
  environment.systemPackages = [ pythonEnv ];
}
