services:
  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    volumes:
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: 
      - ./cloudflare-companion.env
    restart: always

