{ pkgs, lib, cfg }:

with lib;

pkgs.writeShellScriptBin "upload-to-github" ''
  #!${pkgs.bash}/bin/bash
  set -euo pipefail
  
  REPOSITORY=""
  BRANCH="main"
  TOKEN_FILE=""
  SNAPSHOT_FILE=""
  
  # Parse arguments
  while [[ $# -gt 0 ]]; do
    case $1 in
      --repository)
        REPOSITORY="$2"
        shift 2
        ;;
      --branch)
        BRANCH="$2"
        shift 2
        ;;
      --token-file)
        TOKEN_FILE="$2"
        shift 2
        ;;
      --snapshot)
        SNAPSHOT_FILE="$2"
        shift 2
        ;;
      *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
  done
  
  if [ -z "$REPOSITORY" ]; then
    echo "Error: --repository is required (format: owner/repo)"
    exit 1
  fi
  
  if [ -z "$SNAPSHOT_FILE" ] || [ ! -f "$SNAPSHOT_FILE" ]; then
    echo "Error: --snapshot file is required and must exist"
    exit 1
  fi
  
  # Extract owner and repo from repository string
  OWNER=$(echo "$REPOSITORY" | cut -d'/' -f1)
  REPO=$(echo "$REPOSITORY" | cut -d'/' -f2)
  
  if [ -z "$OWNER" ] || [ -z "$REPO" ]; then
    echo "Error: Invalid repository format. Use 'owner/repo'"
    exit 1
  fi
  
  # Get GitHub token
  GITHUB_TOKEN=""
  if [ -n "$TOKEN_FILE" ] && [ -f "$TOKEN_FILE" ]; then
    # If file is encrypted with sops, decrypt it
    if command -v sops >/dev/null 2>&1 && sops -d "$TOKEN_FILE" >/dev/null 2>&1; then
      GITHUB_TOKEN=$(sops -d "$TOKEN_FILE" | tr -d '\n' || cat "$TOKEN_FILE" | tr -d '\n')
    else
      GITHUB_TOKEN=$(cat "$TOKEN_FILE" | tr -d '\n')
    fi
  elif [ -n "${cfg.github.tokenFile}" ] && [ -f "${cfg.github.tokenFile}" ]; then
    if command -v sops >/dev/null 2>&1 && sops -d "${cfg.github.tokenFile}" >/dev/null 2>&1; then
      GITHUB_TOKEN=$(sops -d "${cfg.github.tokenFile}" | tr -d '\n' || cat "${cfg.github.tokenFile}" | tr -d '\n')
    else
      GITHUB_TOKEN=$(cat "${cfg.github.tokenFile}" | tr -d '\n')
    fi
  elif [ -n "$GITHUB_TOKEN" ]; then
    # Use environment variable if set
    GITHUB_TOKEN="$GITHUB_TOKEN"
  else
    echo "Error: GitHub token required. Set --token-file or GITHUB_TOKEN environment variable"
    exit 1
  fi
  
  # Create temporary directory for git operations
  TEMP_DIR=$(mktemp -d)
  trap "rm -rf $TEMP_DIR" EXIT
  
  cd "$TEMP_DIR"
  
  # Clone repository
  echo "📥 Cloning repository..."
  GIT_URL="https://''${GITHUB_TOKEN}@github.com/$REPOSITORY.git"
  if ! git clone --depth 1 --branch "$BRANCH" "$GIT_URL" repo 2>/dev/null; then
    # If branch doesn't exist, create it
    git clone --depth 1 "$GIT_URL" repo
    cd repo
    git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"
  else
    cd repo
  fi
  
  # Create snapshots directory if it doesn't exist
  mkdir -p snapshots
  
  # Copy snapshot file
  SNAPSHOT_NAME=$(basename "$SNAPSHOT_FILE")
  cp "$SNAPSHOT_FILE" "snapshots/$SNAPSHOT_NAME"
  
  # Create or update README
  if [ ! -f "snapshots/README.md" ]; then
    cat > "snapshots/README.md" <<EOF
# System Snapshots

This directory contains encrypted system snapshots generated by NixOS Control Center.

**⚠️ WARNING: These files may contain sensitive information. Do not share publicly.**

## Files

- All snapshot files are encrypted
- Use \`ncc-discover --decrypt\` to decrypt snapshots
- Snapshots are automatically generated and uploaded

## Latest Snapshot

- **File**: \`$SNAPSHOT_NAME\`
- **Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
EOF
  else
    # Update README with latest snapshot info
    sed -i "s|^-\*\*File\*\*:.*|- **File**: \`$SNAPSHOT_NAME\`|" snapshots/README.md
    sed -i "s|^-\*\*Generated\*\*:.*|- **Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")|" snapshots/README.md
  fi
  
  # Commit and push
  git config user.name "NixOS Control Center"
  git config user.email "ncc@localhost"
  
  git add snapshots/
  git commit -m "Add system snapshot: $SNAPSHOT_NAME" || echo "No changes to commit"
  
  echo "📤 Pushing to GitHub..."
  git push origin "$BRANCH" || {
    echo "❌ Failed to push to GitHub"
    exit 1
  }
  
  echo "✅ Successfully uploaded to GitHub: https://github.com/$REPOSITORY/tree/$BRANCH/snapshots"
''

