services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    env_file:
      - plex.env
    dns:
      - 1.1.1.1
    volumes:
      - ./plex/library:/config
      - ./plex/tv:/tv
      - ./plex/movies:/movies
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.plex-secure.entrypoints=websecure"
      - "traefik.http.routers.plex-secure.middlewares=default@file,plex-whitelist@docker"
      - "traefik.http.routers.plex-secure.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex-secure.service=plex"
      - "traefik.http.routers.plex-secure.tls=true"
      - "traefik.http.routers.plex-secure.tls.certresolver=http_resolver"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.middlewares.plex-whitelist.ipwhitelist.sourcerange=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12"

networks:
  proxy:
    external: true
