''
  echo "Aliases set for development:"
  echo "  py   -> Python interpreter"
  echo "  run  -> Start main application"
  echo "  rundebug -> Start main application in debug mode"
  echo "  fmt  -> Format code with Black"
  echo "  lint -> Lint code with Flake8"
  echo "  typecheck -> Run Mypy for type checking"
  echo "  doc -> Generate documentation"
  echo "  sysmon -> Start system monitor module"
  
  echo "Test aliases set:"
  echo "  pt       -> Run all tests"
  echo "  ptf      -> Run tests with full strategy"
  echo "  ptv      -> Run tests validate-only"
  echo "  ptvv     -> Run tests very verbose"
  echo "  pt-basic -> Run basic tests"
  echo "  pt-profiles -> Run profile tests"
  echo "  pt-hardware -> Run hardware tests"
  echo "  pt-failed   -> Run failed tests"
  echo "  pt-first    -> Run failed tests first"
  echo "  pt-log      -> Run tests with logs"
  echo "  pt-random   -> Run marked random tests"
  echo "  ptr N     -> Run N random tests with full strategy"
  echo "  ptrv N    -> Run N random tests validate-only"
''