# app/shell/install/hooks/welcome.nix
{ pkgs }:

''
  echo ""
  echo "╔════════════════════════════════════════╗"
  echo "║  NixOS Control Center - Install Shell  ║"
  echo "╚════════════════════════════════════════╝"
  echo ""
  echo "Welcome to the NixOS installation environment!"
  echo ""
  echo "Installation Modes:"
  echo "----------------------------------------"
  echo "Basic Installation:"
  echo "  install            - Interactive install (GUI if display, else TUI)"
  echo "  install-gui        - Force graphical wizard (PySide6)"
  echo "  install-fzf        - Force terminal fzf menus"
  echo "  install-tui        - (deprecated) same as install-fzf"
  echo "  install-dry        - Dry-run (wizard only, no writes/deploy)"
  echo "  (from host)        - NCC_DRY_RUN=1 nix-shell"
  echo "  (shell only)       - NCC_INSTALL_SHELL_ONLY=1 nix-shell"
  echo ""
  echo "Profile Installation:"
  echo "  install-desktop    - Desktop environment"
  echo "  install-server     - Server configuration"
  echo "  install-dev        - Development setup"
  echo "  install-gaming     - Gaming optimized"
  echo ""
  echo "Type 'show-help' for all available commands"
  echo "----------------------------------------"
  echo ""
''