services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      proxy:
    dns:
      - 1.1.1.1
    labels:
      # Basis-Konfiguration
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      # Router Konfiguration
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=http_resolver"
      
      # Service Konfiguration
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      
      # Maximale Sicherheit mit allen Middlewares
      - "traefik.http.routers.portainer.middlewares=default@file,traefikAuth@file,admin-whitelist@file" # ,rate-limit@docker"
      
      # Sticky Sessions
      - "traefik.http.services.portainer.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.portainer.loadbalancer.sticky.cookie.secure=true"
    restart: unless-stopped

networks:
  proxy:
    external: true
