
# This file is generated by the NixOS Control Center
{
  # System Configuration
  systemType = "gaming-workstation";
  hostName = "testhost";
  testing = true;  # Test-Modus aktiviert
  
  # ... Rest der Konfiguration ...
}
