{ lib, pkgs }:

{
  exportMarkdown = { sessionDir, sessionId }: ''
    export_markdown() {
      local session_dir="${sessionDir}"
      local md_file="$session_dir/report.md"

      # Add session metadata
      local session_json="$session_dir/session.json"
      local start_time=$(${pkgs.jq}/bin/jq -r '.start_time' "$session_json")
      local end_time=$(${pkgs.jq}/bin/jq -r '.end_time // "Recording in progress"' "$session_json")
      local backend=$(${pkgs.jq}/bin/jq -r '.backend' "$session_json")
      local hostname=$(${pkgs.jq}/bin/jq -r '.hostname' "$session_json")
      local user=$(${pkgs.jq}/bin/jq -r '.user' "$session_json")
      local total_steps=$(${pkgs.jq}/bin/jq -r '.total_steps // "Recording in progress"' "$session_json")

      cat > "$md_file" << EOF
# 📝 Problem Steps Recorder Report

## Session Information

- **Session ID:** ${sessionId}
- **Start Time:** $start_time
- **End Time:** $end_time
- **Backend:** $backend
- **Hostname:** $hostname
- **User:** $user
- **Total Steps:** $total_steps

---

## Steps

EOF

      # Add steps
      local steps_dir="$session_dir/steps"
      if [ -d "$steps_dir" ]; then
        for step_file in "$steps_dir"/step_*.json; do
          if [ -f "$step_file" ]; then
            local step_num=$(${pkgs.jq}/bin/jq -r '.step' "$step_file")
            local description=$(${pkgs.jq}/bin/jq -r '.description' "$step_file")
            local window_title=$(${pkgs.jq}/bin/jq -r '.window_title' "$step_file")
            local app_name=$(${pkgs.jq}/bin/jq -r '.app_name' "$step_file")
            local screenshot=$(${pkgs.jq}/bin/jq -r '.screenshot' "$step_file")

            cat >> "$md_file" << EOF
### Step $step_num: $window_title ($app_name)

**Description:** $description

EOF

            if [ "$screenshot" != "null" ] && [ -n "$screenshot" ]; then
              cat >> "$md_file" << EOF
![Step $step_num Screenshot](steps/$screenshot)

EOF
            else
              cat >> "$md_file" << EOF
_No screenshot available for this step_

EOF
            fi

            echo "---" >> "$md_file"
            echo "" >> "$md_file"
          fi
        done
      fi

      cat >> "$md_file" << EOF

---

*Generated by NixOS Step Recorder*
EOF

      log "Markdown report generated: $md_file"
    }
  '';
}
